### ISSUE TITLE
Pages: Overview as tree

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#10]
Create an overview of all pages in a tree.

This should include:
- [x] tree view
- [x] Drag & Drop page to other location in tree
- [x] Revision status
- [x] Translation status
- [x] Exclude archived pages
- [x] show only pages of current site

**Comment by timoludwig** [comment]
- show only pages of current site

**Comment by svenseeberg** [comment]
@timoludwig I do not understand your added bullet point. Do you mean that each city/region/site should only see their own pages?

**Comment by timoludwig** [comment]
Yes, at the moment the pages overview/list shows all pages of all sites.
In order to enable multisite support, we have to limit the list to only the pages of the current site.
There is a [multisite framework](https://docs.djangoproject.com/en/1.11/ref/contrib/sites/) in the django core library which does that automatically, so I will check whether this can be extended to our needs.
