### ISSUE TITLE
Make it possible to filter for unused media elements

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1005]
### Motivation

In the media library, it should be possible to filter for all media elements which are not embedded in any pages/events/pois and are not used as icon of any object.

### Proposed Solution

Evaluate possible approaches for this task, e.g. whether we should store this information somewhere in the database and update it every time a media element is inserted into a page, or whether this should be "calculated" at runtime by scanning the whole content for occurrences of the media file's absolute paths.

**Comment by ulliholtgrave** [comment]
I agree that this should be come in handy, but as for the migration we can focus on only migrating used media files. Therefore, I would leave it on the Version 2.0 milestone.

**Comment by JanErikHuehne** [comment]
Is there any consent on how this should be implemented? Scanning at runtime sounds very slow to me. So should we only perform this one time scan during migration and add fields to media files that get set if they are added / removed somewhere? Maybe a decorator implementation to all functions involving  media files might be a good idea to check it? Otherwise, there will a lot of redundant code I assume.

**Comment by JanErikHuehne** [comment]
I see. I´m on it. Thanks for the input :+1:
