### ISSUE TITLE
POIs can no longer be created from event form

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1166]
### Describe the Bug

Even for superuser it is no longer possible to create a POI from the event form. Probably a permission issue.

### Additional Information

![image](https://user-images.githubusercontent.com/15608678/154031085-74de7527-3189-474e-8ad3-e29683312c12.png)

**Comment by ulliholtgrave** [comment]
Seemed to be a local caching problem.

**Comment by ulliholtgrave** [comment]
Okay, this is a browser-specific event. Firefox seems to work, but chrome and opera not

**Comment by timoludwig** [comment]
I could reproduce this in Chromium.
When the POI creation is the only option in the dropdown, the entry is automatically selected and apparently Chromium does not trigger an event when this element is clicked.
On firefox, this problem doesn't exist, because the event is triggered every time interdependently of whether it's already pre-selected.
