### ISSUE TITLE
Missing Linkcheck migrations

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1205]
### Describe the Bug
The linkcheck app is missing migrations.

### Steps to Reproduce
```
# integreat-cms-cli migrate
Operations to perform:
  Apply all migrations: auth, cms, contenttypes, linkcheck, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'linkcheck' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by timoludwig** [comment]
I guess this is due to the change from `AutoField` to `BigAutoField` for automatic primary key fields in Django 3.2?
I think this is a bug of the linkcheck library itself, which should define their `default_auto_field = 'django.db.models.AutoField'` if they still use the legacy field. 
In the meantime, we can either create migrations manually or override the app config ourselves: https://stackoverflow.com/a/67007098

**Comment by timoludwig** [comment]
For reference: I created https://github.com/DjangoAdminHackers/django-linkcheck/issues/137 in the upstream repo so we might be able to remove our workaround at some point.
