### ISSUE TITLE
XLIFF files imported as draft translations

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1284]
### Describe the Bug
After importing translations from XLIFF files the status of the translation is set to draft.

### Steps to Reproduce

1. Open https://malte-test.tuerantuer.org/gumv/pages/de/
1. Select the Ukraine zip file and import
1. Translations are imported, but status is set to draft.

### Expected Behavior
Pages should be visible.

### Additional Information
The issue description is probably incomplete.

**Comment by timoludwig** [comment]
This happens when no translation exists for the imported language or the latest translation is a draft.

**Comment by svenseeberg** [comment]
That means the translation should inherit the status of the source at the time of export? :thinking: And we make it 2 bulk actions "Export published versions as XLIFF" vs "Export most current versions as XLIFF"?

**Comment by timoludwig** [comment]
I'm not sure, I would prefer the solution to just export public versions and set the status to public for all imported versions again. For edge cases where drafts should be exported, we could suggest the workaround to publish them temporarily, export them as XLIFF and hide them again? But this is no real use case I think, since in most cases the translation should only happen when the content is finished and not a draft anymore.
