### ISSUE TITLE
Add missing translation to translation report

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1440]
### Motivation

Besides the outdated translations we also want to see how many words are missing translations in each language.

### Proposed Solution

Add counter of missing translations and extend the table on the translation coverage.

**Comment by osmers** [comment]
We advocate for implementing this feature sooner rather than later, especially if the effort is low. Daniel went to check the WP system today to get a number for a translation cost estimate. 
The question remains whether outdated and missing translations should be combined in one figure or could be shown in two columns or something...what do you think?
