### ISSUE TITLE
Use gender-sensitive language

### ISSUE THREAD

**Issue by karthik-integreat** [digitalfabrik/integreat-cms#1456]
### Motivation

The backend does not have gendering in the roles. For eg: Redakteur, Author., Erfahrener Anwender. 

### Proposed Solution

The first step is to to gender the simple words, no composite taksks.
Use Redaktion instead of Redakteur...
Use Konto instead of benutzerkonto
Use Anwender:in instead of Anwender etc...
### Alternatives

Where it is not possible, for eg. where there are composite words, then we should think about using neutral expressions.

**Comment by JoeyStk** [comment]
Thank you very much for reporting this issue. I had some time over the weekend to have a look at this. And I still have a bunch of questions left: 

- I would like to find a rule of thumb of what words we'd prefer to use and like them to be the same all through the cms. I made a list of words and their use-cases. Could you please discuss this with your the other members of the service team and find a synonym that you would prefer? Later I could change these words by the time this issue increased priority. 

word | Use cases | suggestions
-------- | -------- | -------- 
Benutzer | Benutzer, Benutzer (Pl.), dem Benutzer (Dativ), Benutzerdefinierter Zeitraum | Benutzer:in, Benutzer:innen, dem:der Benutzer:in or dem:r Benutzer:in or der:m Benuter:in, Benutzer:innendefinierter Zeitraum
Redakteur | Redakteure (Pl.) | Redakteur:innen or Redakteure:innen
Bearbeiter | Bearbeiter | Bearbeitende Person or Bearbeiter:in
Mitarbeiter | Mitarbeiter, Mitarbeiter (Pl.), keine Mitarbeiter | Mitarbeitende Person or Mitarbeiter:in, Mitarbeitende (Pl.) or Mitarbeiter:innen, keine mitarbeitende Person or kein:e Mitarbeiter:in

These were the more difficult words where I didn't feel comforatable to make a decision by myself.
Furthermore I found two other words, that I stumbled upon. 

- We still use „Kommunen-Team" and "Promo Team“. I would change them to „Service-Team“ and „Marketing Team“, as we already do in our everyday language. Is this fine by you or do you have any objections?

- I would also consider changing the german translation of belarus from „Weißrussland“ to „Belarus“. Due to the political movements during the last years there have been linguists who voiced their disapproval of the translation „Weißrussland“, and preferred „Belarus“, since it does not suggest as much dependency to Russia. However this is still a disputed topic, and maybe we should ask colleagues from the Service Team which version they prefer. For more context please check out: https://de.wikipedia.org/wiki/Belarus#%E2%80%9EWei%C3%9Frussland%E2%80%9C_und_%E2%80%9EBelarus%E2%80%9C. Note here: Also Wikipedia changed their entry from „Weißrussland“ to „Belarus“.

@karthik-integreat

**Comment by JoeyStk** [comment]
Thank you a lot for your ideas. I think I'd still wait until the service-team has their opinion on this topic.
I have one more thought on this. Since we now also have a dutch translation file, we could consider also making the dutch translation gender-sensitive. For general background on how gender in language is handled in dutch please check out the following [link](https://www.gespraechswert.de/gendern-international/#niederlaendisch-gendern).

**Comment by karthik-integreat** [comment]
I agree with Timos suggestion, except for Bearbeiter and Redakteur:in. I am not sure if Redakteur:in is appropriate. Why not use Redaktion in both these cases? It would be more neutral. 

>   We still use „Kommunen-Team" and "Promo Team“. I would change them to „Service-Team“ and „Marketing Team“, as we already do in our everyday language.
>         I would also consider changing the german translation of belarus from „Weißrussland“ to „Belarus“.

  Agree completely.

**Comment by karthik-integreat** [comment]
My personal preference would also be to use * instead of :
