### ISSUE TITLE
False positive error message for urlencoded filenames in PDF export

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1499]
### Describe the Bug

When filenames which contain umlaute are urlencoded in the src attribute, they cause error messages in the PDF export 

### Steps to Reproduce

Create PDF which contains images with umlaute in their filename

### Expected Behavior

The images are contained in the PDF, so no error should appear

### Actual Behavior

An error is displayed in the logfile:

  ```
May 25 12:26:44 ERROR   integreat_cms.cms.utils.pdf_utils - The file '/var/www/integreat-cms/media/regions/206/2022/01/h%C3%A4usliche-gewalt.jpg' was not found in the media directories.
  ```

Even though the file exists:

  ```
$ ls /var/www/integreat-cms/media/regions/206/2022/01/häusliche-gewalt.jpg
/var/www/integreat-cms/media/regions/206/2022/01/häusliche-gewalt.jpg
  ```

**Comment by jonbulz** [comment]
TL,DR: I think even though the error appears in the logs, images with Umlauten are actually rendered in PDFs, but the rendering is broken in general and images are weirdly stacked on top of each other.


I'm not sure if I'm catching all there is here, but this is difficult to reproduce for me. I'll try my best to explain what I experienced so far. I'm having two files, [test.jpg](https://user-images.githubusercontent.com/101657168/186887971-43e98f7c-385a-43c1-87a6-f3ea0bbc7227.jpg) and [täst.jpg](https://user-images.githubusercontent.com/101657168/186888141-326eb7cb-d1a4-4fac-bc74-50516e5b1021.jpg).

First off, I'm always getting the error in the logs when using image files with Umlaute as src. However, the PDF still seems to render correctly. Eg. 
```<p><a href="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg" alt=""></a></p>```
gives the expected [täst.pdf](https://github.com/digitalfabrik/integreat-cms/files/9432450/tast.pdf).


BUT as soon as I include multiple images, it gets weirder. For example
```<p><a href="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg" alt=""></a><a href="http://localhost:8000/media/regions/1/2022/08/test.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/test.jpg" alt=""></a></p>``` 
renders this [PDF](https://github.com/digitalfabrik/integreat-cms/files/9432488/both_with_tast_first.pdf) and
```<p><a href="http://localhost:8000/media/regions/1/2022/08/test.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/test.jpg" alt=""></a><a href="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg" alt=""></a></p>```
gives [this](https://github.com/digitalfabrik/integreat-cms/files/9432503/both_with_test_first.pdf).
However, I believe this is just because the images are stacked incorrectly, because I can render them "correctly" with some
[placeholder](https://github.com/digitalfabrik/integreat-cms/files/9432545/placeholder.pdf) text in between for 
```<p><a href="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg" alt=""></a>placeholder<a href="http://localhost:8000/media/regions/1/2022/08/test.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/test.jpg" alt=""></a></p>```

But maybe you experienced a different behavior? Were there other images in the HTML that you tried to render?

**Comment by charludo** [comment]
> BUT as soon as I include multiple images, it gets weirder. For example `<p><a href="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/t%C3%A4st.jpg" alt=""></a><a href="http://localhost:8000/media/regions/1/2022/08/test.jpg"><img src="http://localhost:8000/media/regions/1/2022/08/test.jpg" alt=""></a></p>` renders this [PDF](https://github.com/digitalfabrik/integreat-cms/files/9432488/both_with_tast_first.pdf) 

Not exactly. Your test images have a white background, same as the PDF, so it's impossible to see in your examples, but both images do get rendered. However, they do not line break, and the second one overflows to the right of the pdf.

Since the second image has a thick white left border, you simply can´t see it in the example. Iǘe attached a different example where you can see it [here](https://github.com/digitalfabrik/integreat-cms/files/9783770/Integreat.-.German.-.Stadtplan.pdf)

You are correct however in that this has nothing to do with Umlaute.

**Comment by charludo** [comment]
> So in other words, the problem is just the incorrect logging message, right?
> 
> I would consider the missing line break of images "expected behavior"... If the region managers notice this problem, they can simply solve it by reducing the width of the images until they fit on the page.

Hm, wish I'd read that before trying to figure out a css solution 😆 

Sadly, since `xhtml2pdf` is limited to (mostly) CSS2, I don't believe there is a usable solution. Best I could come up with fixes the problem, but if there are multiple links on the same line, each containing at least on image, the formatting of all but the first of those links gets broken:

```css
p a img {
    display: block;
}
p a:first-child img {
    display: inline-block;
}
```

I don't know how common this is. I haven't seen an actual occurrence of this anywhere, at least. But it just swaps one unexpected behaviour for another.

Plus, I actually found it really difficult to produce the original bug with just the WYSIWYG editor, and had to switch to HTML for this. 

Please let me know whether or not to include the CSS "fix" in the PR.

**Comment by timoludwig** [comment]
> Please let me know whether or not to include the CSS "fix" in the PR.

Thanks a lot for looking into this! Yes I think the workaround is actually an improvement, since I think it is more likely that users place images next to each other than mixing it with links with specific formatting which needs to be preserved.
It is however another problem than this issue, so I will open a new one for this.
