### ISSUE TITLE
Very long titles in order field in page form are breaking layout

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1540]
### Describe the Bug

If we create a page with an extremely long title, this breaks the page form due to an expansion of the order field.

### Expected Behavior

Long titles shouldn't affect the whole layout due to shortening of the displayed title.

### Actual Behavior

The order box gets expanded to match the long title and breaks the layout

### Additional Information

![grafik](https://user-images.githubusercontent.com/15608678/173305884-44bd44f5-97bd-4dac-97ef-7d66c63a6051.png)

**Comment by david-venhoff** [comment]
This issue should have been fixed by #1527. The fix at least works for me locally: 
![grafik](https://user-images.githubusercontent.com/78504586/173386493-e1299862-21e6-41f6-9678-bbbb46b59a29.png)

Could you verify that the problem still exists after performing git pull and clearing the browser cache?

**Comment by timoludwig** [comment]
@david-venhoff yes indeed, this has been fixed by #1527, thanks! :pray:
