### ISSUE TITLE
Broken Links from old revisions are shown

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1604]
### Describe the Bug
After cloning lkkarlsruhe to mannheim we found broken links from old revisions of pages in "draft" status. Those pages/old revision should not be crawled by the broken-link checker.

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by timoludwig** [comment]
Probably this is related to https://github.com/digitalfabrik/integreat-cms/issues/1572

**Comment by timoludwig** [comment]
I was not able to reproduce this locally. When I save a new revision of a page, the old link objects are being deleted:

https://github.com/digitalfabrik/integreat-cms/blob/02a4d49bc0ec47ed0c2bb2786e9a0c61dd7dad73/integreat_cms/cms/forms/pages/page_translation_form.py#L84-L85

If anyone manages to reproduce this problem, try to describe it as detailed as possible.
Maybe this is not a problem of the code base, but a problem resulting of inconsistencies in the production database instead?
Requires further investigation before we can fix this issue.

**Comment by timoludwig** [comment]
@dkehne and just to clarify: Broken links in draft translations (if they are the most recent ones) should be shown, right? Just not in the old versions of it?
E.g. if we have a translation with
- version 1: broken links A, B, X, Y
- version 2: broken links B, C, Y, Z

Then, in the broken link checker, the links B, C, Y, Z should be listed, even though the page is a draft, right? And only A and X should be excluded because they're outdated...

**Comment by MizukiTemma** [comment]
I'm not sure whether this is the case which @dkehne has originally reported but found a suspicious case:

1) Publish a new page with 1 link. This link is detected by the link checker.
2) Add another link to the page and update it. Those both links are detected by the link checker.
3) Restore and publish the version with one link. The linkchecker still shows both the links.

**Comment by timoludwig** [comment]
@MizukiTemma good catch! I can also reproduce this bug. This could definitely be the cause of this problem.
