### ISSUE TITLE
Investigate why the standard cacheops invalidation procedure isn't triggered

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1618]
### Describe the Bug

We seem to have a problem with cacheops not invalidating our cache after we delete or update our objects (e.g. language nodes). To mitigate this behavior we manually invalidate the cache (see #1534), but it would be better to get the in-built function working.

### Additional Information

See cacheops documentation: https://github.com/Suor/django-cacheops

**Comment by ulliholtgrave** [comment]
Right now I can think of three possible problems:

-     The invalidation is handled asynchronous and opening the page tree right after the deletion/movement of the nodes results in a display of the not-yet invalidated state
-     Our inheritance model isn't handled correctly by cacheops
-     The caching of the views isn't correctly invalidated

**Comment by timoludwig** [comment]
I'm not sure whether we really have a general problem here. The way I understand it is that the cacheops invalidation is working exactly as documented. The problem is just that cacheops cannot know that e.g. the pages are affected from changes of the language tree, since the pages are only linked to the language model and not to the language tree node model. So I guess for this specific case we need the manual invalidation anyway and for normal cases the cacheops invalidation works fine. If we notice other edge cases where the standard invalidation doesn't work, we should open separate issues for it...

**Comment by ulliholtgrave** [comment]
Okay, I understand your problem with the issue. I somehow would prefer a more elegant way than iterating through all objects, but I guess we can close the issue.
