### ISSUE TITLE
"Minor Edit"-Button changes translation status nevertheless

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1653]
The "Minor Change - please do not translate button" does not work. The translations are updated nevertheless.

### Steps to Reproduce
I updated the icon of this page: https://admin.integreat-app.de/bochum/pages/de/1252/edit/
I checked the "Geringfügige Änderung, please do not update translation status"-mark and clicked on save
The translation status of alle translations changed.

### Expected Behavior
Translation status should NOT be updated, when the checkbox is ticked.

**Comment by dkehne** [comment]
Prio High.

**Comment by svenseeberg** [comment]
I cannot confirm that the problem exists. When setting the minor edit flag the status of depending translations does not change when changing the page icon or content.

**Comment by timoludwig** [comment]
I think the problem arose because no changes were made to the content of the translation - so no new version was created, and just the "minor edit" field of the existing translation was toggled and the date was updated, which caused the dependent translations to be outdated.

One way to fix this issue would be to create new translation versions even if the content did not change... this inflates the version history a bit, but would reflect the translation status better.

Another possibility would be to not update the timestamp of the translation when no changes are made, but this behavior was explicitly requested to be able to refresh the date without performing changes.

**Comment by dkehne** [comment]
I do know if the fact that live-content is also used on this page, matters.

**Comment by svenseeberg** [comment]
> One way to fix this issue would be to create new translation versions even if the content did not change... this inflates the version history a bit, but would reflect the translation status better.

Agreed, we should probably do that.

**Comment by ulliholtgrave** [comment]
> I think the problem arose because no changes were made to the content of the translation - so no new version was created, and just the "minor edit" field of the existing translation was toggled and the date was updated, which caused the dependent translations to be outdated.

But as we confirm the up-to-dateness of a translation with no changing content, we should probably consider not changing the the translation status at all. The content is the same and in my opinion the "marks as up-to-date" functionality should be independent.

**Comment by timoludwig** [comment]
> But as we confirm the up-to-dateness of a translation with no changing content, we should probably consider not changing the the translation status at all. The content is the same and in my opinion the "marks as up-to-date" functionality should be independent.

Yes, I think this would be the case when we just create a new translation object (with automatically setting the minor edit field to true) instead of modifying the last updated date of the existing translation (like we do at the moment).
