### ISSUE TITLE
Fix issues with dutch translation file

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#1665]
### Describe the Bug
Inside the dutch translation file there have been a few issues. For some translations there is still the German translation instead of the dutch translation.

### Steps to Reproduce
- Checkout for example the translation for "Go back to imprint editor"

### Expected Behavior
- All dutch translations, no German translations

### Actual Behavior
- There are still some German translations

**Comment by timoludwig** [comment]
You are referring to the lines from [7116](https://github.com/digitalfabrik/integreat-cms/blob/9d5ccffbb5e4723bbf976d6bc5dd9c419ab7c598/integreat_cms/locale/nl/LC_MESSAGES/django.po#L7116-L8688) upwards, right? These are just unused strings and are there in case a previously translated string gets re-added to the source code.
In this case, I think it does not make sense to translate them manually - just deleting the unused lines and translating new strings once they appear might be a more sensible approach.

Apart from that, I would not create issues for small problems with the Dutch translation file, since we can probably not guarantee that with every PR, we translate all strings into Dutch (if neither the PR author, nor the reviewer understand Dutch, this is a bit hard)...
I think it's fine if we treat Dutch as a language for which it's cool that we have translations, but not a big problem if there are some places where the translations are outdated...
