### ISSUE TITLE
Include overall word count in translation report

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#1845]
### Motivation
If we want to translate a new language, it is good to be able to tell the Kommunen approx. how many words they have in their German content.

### Proposed Solution
Include Word count of German (overall, with possible addition to see distinction between published and draft versions) - does not have to be in the translation report, as we used to have it since it is mainly for the service team to check

### Alternatives
Enable a new language and see how many words are missing. Definitely an alternative and the way we will use it till the feature is available. 

### Additional Context
We used to have German as a translation in the translation report, bcs that is how you see German, as a translation. We took it out bcs it is confusing for the users. Maybe we can include this count in a new location - maybe once we have the translation section for automated translations?

### Design Requirements
Als Service Team möchte ich mit einem Klick sehen können, wie viele Wörter der deutsche Inhalt hat
Als Service Team möchte ich sagen können, wieviele Wörter veröffentlicht und wieviele Wörter im Entwurf sind

**Comment by timoludwig** [comment]
@osmers How to handle pages that have both - a public version and a (newer) draft/autosave version?
Should only the newest version of this page be included in the draft/autosave counter, or also count for the public words? Since the motivation behind this is the translations costs, I guess it would be more accurate to include it in the public counter as well, so if the region asks "How many words would there be if we translated all public versions", then the answer could be derived from the table?

It just has the caveat that if the region asks "How many words are there in public and draft pages" we couldn't just add the two numbers, since the resulting words would be more than the actual words...

**Comment by osmers** [comment]
@timoludwig Hmmm, that is a very good question...generally I only translate what is published. I would therefore suggest, that we count pages with their last version. So maybe we can have a number for each category of the state of publication? Then the municipalities/we can just add up numbers. 
If a page has an autosave version as the latest version, then count it towards autosaved pages. Bcs I either need to accept or reject the autosave - I cannot translate the last public version without doing that, right?

**Comment by osmers** [comment]
@MizukiTemma looks good I think :) makes sense to me
