### ISSUE TITLE
Not possible to update translation status without changing content

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#1864]
### Describe the Bug
I can't get the translation status to update, even when removing the small edit check box bcs as soon as I click on update, it resets the check box to checked: 
You can test it here: https://admin.integreat-app.de/waldeck-frankenberg/pages/en/23071/edit/

### Steps to Reproduce

1. Go to https://admin.integreat-app.de/waldeck-frankenberg/pages/en/23071/edit/
2. Uncheck the "Small Edit" box
3. Click on "Update"
4. See that the check box is checked again and the status of the translation is not updated

### Expected Behavior
Status of translation should be updated and checkbox should remain unchecked

### Actual Behavior
Status of translation stays the same and check box is checked again.

### Additional Information
Might have to do with the fact that no editing was done in the text, thus the system "assumes" that it is a minor edit.

**Comment by osmers** [comment]
Maybe we can remove the check box for languages that don't have another dependent language?

**Comment by osmers** [comment]
> > Maybe we can remove the check box for languages that don't have another dependent language?
> 
> No, since we need the possibility to keep the "outdated" status for them...
> 
> E.g. if a page is outdated, then you fix a typo but still want to know that it's outdated and need to update the translation next time you start the translation process...

Fair enough - so it is actually not a check box just for the dependent languages but for the language itself as well? Somehow the function seems different to me than it is for the German page...

**Comment by osmers** [comment]
But I remember that we talked about that and changed the description...

**Comment by timoludwig** [comment]
> But I remember that we talked about that and changed the description...

Yes, exactly, the effect is slightly different and we explain it (hopefully users read this text at all :see_no_evil:)
| Default language | Other languages |
| --- | --- |
| ![Screenshot 2022-11-15 at 17-48-32 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/201978299-23fd0e4d-b9ac-4534-95af-74a85dc1bf35.png) | ![Screenshot 2022-11-15 at 17-48-22 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/201978306-3dd9da40-f5b3-4991-b147-7f9960c4232e.png) |


> I think the problem comes into existence, when someone carelessly changes something small within the German translation and forgets to check the minor edit box. Then they go and want to update the translation status again of the other languages, so it is up to date again bcs really they did not change anything, hit the update button and nothing changes, bcs they did not change anything in the text... Somehow we need to make this more intuitive or understandable...but I don't know how

Well, one way is the "Refresh date" function for entire pages... but I agree that this is probably not the most intuitive...

Maybe we could change our "automatic-minor-enforcement-rule" to only set the minor edit flag if something was changed in the page-section of the form (e.g. changed the order or changed the icon)? So the following logic would apply:
- Content changed -> no minor edit (as before)
- Content did not change, but something in the "Settings of the page" section changed (e.g. order, icon, or live content) -> set minor edit flag, because update is for all translations and should not influence the translation status (as before)
- Nothing at all changed -> do not set minor edit flag and mark page as up to date (new behaviour)

Do you think this makes sense?

**Comment by osmers** [comment]
So that would imply that when I open a page that is marked as outdated, and I press the "update" button, the status should be updated bcs the minor edit box will not be checked, right?
Or rather I think my question is, whether this "rule" is started every time I open a page...not sure if I am explaining this right :D
But if your answer to my question is yes, then I think I agree with your proposal
Just trying to think of  a scenario where that might present a problem...but generally, if I open a page and don't change anything, I either go back (not clicking update) or have the intention of changing the status of the translation, thus clicking update (which would be ok, bcs it then works as intended).

**Comment by timoludwig** [comment]
> So that would imply that when I open a page that is marked as outdated, and I press the "update" button, the status should be updated bcs the minor edit box will not be checked, right?

Exactly, yes. The only case where the status would stay "outdated" is when I either tick the "minor edit" box explicitly or I make some changes to the settings without changing the content.

> but generally, if I open a page and don't change anything, I either go back (not clicking update) or have the intention of changing the status of the translation, thus clicking update (which would be ok, bcs it then works as intended).

Yes, sounds reasonable.
