### ISSUE TITLE
Character count in news not working

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#1886]
### Describe the Bug

In news form the number of characters typed by user should be live counted and shown in the left bottom corer.

### Steps to Reproduce

1. Go to 'News'
2. Click on 'Create news message'
3. Type some letters in 'content'
4. See the left bottom corner.

### Expected Behavior

The number of characters is counted and shown live, like '42/250'.

### Actual Behavior

The number of characters is not shown (it remains only '/250').

![charsNotCountedInNews](https://user-images.githubusercontent.com/82345046/203337286-a1aadf0b-d98f-4143-8b75-5add76120999.png)

**Comment by charludo** [comment]
Just ran a git bisect, looks like you found the first error caused by the linter refactor 😅

**Comment by charludo** [comment]
This is very strange. The reason it's not working anymore is because the [`charCounter`](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/static/src/js/charCounter.ts) querys for `textarea[name^=form-][name$=-text]`. However, the forms are now called `translations-0-text`, `translations-1-text` and so on (instead of `form-0-text` etc.).

For the life of me, I can't find where this name is set in the first place, much less where the linter PR could have influenced it.

**Comment by timoludwig** [comment]
> For the life of me, I can't find where this name is set in the first place, much less where the linter PR could have influenced it.

Thanks for figuring that out!
Then you're off the hook and it's my fault when I refactored the formset to use [inlineformset_factory](https://docs.djangoproject.com/en/3.2/ref/forms/models/#inlineformset-factory) instead of [modelformset_factory](https://docs.djangoproject.com/en/3.2/ref/forms/models/#django.forms.models.modelformset_factory) in https://github.com/digitalfabrik/integreat-cms/commit/1f1ab371fee1b7a57ef678f97c7c32f4e00189b2 :innocent:

**Comment by charludo** [comment]
> > For the life of me, I can't find where this name is set in the first place, much less where the linter PR could have influenced it.
> 
> Thanks for figuring that out! Then you're off the hook and it's my fault when I refactored the formset to use [inlineformset_factory](https://docs.djangoproject.com/en/3.2/ref/forms/models/#inlineformset-factory) instead of [modelformset_factory](https://docs.djangoproject.com/en/3.2/ref/forms/models/#django.forms.models.modelformset_factory) in [1f1ab37](https://github.com/digitalfabrik/integreat-cms/commit/1f1ab371fee1b7a57ef678f97c7c32f4e00189b2) innocent

Oh, than I guess I mis-read the bisect, whoops.

Iĺl just open a PR with the regex changed?
