### ISSUE TITLE
Add possibility to disable specific languages for machine translations

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#1927]
### Motivation
In our machine translation management section we want to add an overview of the available languages.

### Proposed Solution
- [ ] Add a new (array ?) field to the region model to store all enabled/disabled languages for machine translations
- [ ] Add a form to change these languages to the machine translation management section
- [ ] In all places where machine translations are generated, first check whether the corresponding language is enabled for machine translations in this region.

### Additional Context
Part of our meta issue for machine translations

This depends on:
- [x] #1831 

### Design Requirements

![language selection](https://user-images.githubusercontent.com/16021269/204850134-4db8ca5c-a706-4597-80ad-257c13e49860.png)
— [Source](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=166%3A1980)

**Comment by timoludwig** [comment]
@nikolahoff How was this supposed to work, is this just a read-only overview over all languages which are available for machine translations, or should it also be possible to disable specific languages (even if they are available)?

**Comment by osmers** [comment]
@timoludwig it should be possible to disable specific languages, even if they are theoretically available for MT. The idea is that certain partners might say that the quality of a specific language is too poor for their standard, which is why they disable it altogether.

**Comment by charludo** [comment]
Is this supposed to disable translations *to* a language, or *from* that language?

And regardless of the answer, don't we also need the opposite direction as well?

e.g. a region does not want to use SUMM.AI, so they disable translation *to* "German (easy)". But they also want to disable translations *from* any language except "German" (e.g. to prevent machine translating machine translations).

Unless this has already been discussed and decided elsewhere, I think the PR for this issue should add 2 new columns, one *from*, one *to*.

**Comment by timoludwig** [comment]
I think this setting is about the target languages. And probably this is sufficient, because the source language is implicitly stated by the language tree? A from & to setting would probably be too complex anyways?

**Comment by charludo** [comment]
> the source language is implicitly stated by the language tree

So it's not possible to translate from anything but the "root" language?

But yes, in that case it's clear.

**Comment by timoludwig** [comment]
Except a region has a nested language tree, e.g. "de -> en -> fr" or something...
Then it would be up to the region managers to disable MT for"en" if they also want to enable them for "fr" and don't want to machine translate already machine translated pages...

**Comment by charludo** [comment]
How do we want to deal with languages without a MT provider? It might be confusing to enable a language in the management section, but then not be able to MT into that language.

How about splitting the list of languages into two, something like this:
![image](https://user-images.githubusercontent.com/47758554/215322555-260a529c-4582-498e-93d3-205e1c4720a8.png)

**Comment by timoludwig** [comment]
> How do we want to deal with languages without a MT provider? It might be confusing to enable a language in the management section, but then not be able to MT into that language.

Hmm, good question. I think I would prefer it to only show languages here which are supported by a MT provider and hide the others. @osmers what do you think?

> Add a new (array ?) field to the region model to store all enabled/disabled languages for machine translations

Also, in contrast to the issue description, maybe adding a new `BooleanField` to the `LanguageTreeNode` model makes more sense than an `ArrayField` or `ManyToManyField` field in the `Region` model?

**Comment by charludo** [comment]
How would a `BooleanField` work?

My original intention was to use an `ArrayField` with `CharField` as its `base_field`. However I've run into an issue where I can't set the `choices` of the `ArrayField` to the region's `active_languages` because they're not available there yet, but setting the `choices` later, the field validation fails - I assume because the available choices aren't in the "original" ones...? Really not sure about this.

My current workaround is having a `CharField` on the region model, wherein the language slugs are saved as CSV. Not ideal, I know.

Though in any case, I'd prefer only saving the disabled languages, then inverting the choice w.r.t. which checkboxes are checked in the management section. That way new languages are enabled by default and without any additional work needed.

**Comment by charludo** [comment]
> only show languages here which are supported by a MT provider

To prevent confusion why some languages are missing, shouldn't we at least list the languages that aren't supported? Not necessarily as checkboxes, just as a list of unsupported languages

**Comment by timoludwig** [comment]
> How would a `BooleanField` work?

Well, we could just add a field `machine_translations_enabled` or similar to the `LanguageTreeNode` model.
Then, in the `TranslationsManagementForm`, we need a new field (probably a [`forms.MultipleChoiceField`](https://docs.djangoproject.com/en/4.1/ref/forms/fields/#multiplechoicefield)with a [`CheckboxSelectMultiple`](https://docs.djangoproject.com/en/4.1/ref/forms/widgets/#checkboxselectmultiple) widget) which is independent from the `fields` attribute of the `Meta` class, because it's not part of the region model and just acts as UI element to render the form. Then, in the form's `save()` method, we iterate over all choices and set `machine_translations_enabled` to the respective value based on whether they were selected or not.

> To prevent confusion why some languages are missing, shouldn't we at least list the languages that aren't supported? Not necessarily as checkboxes, just as a list of unsupported languages

Yes, sounds reasonable :+1:

**Comment by charludo** [comment]
Ohhh sorry, I mis-read your previous comment about adding the field to the `LanguageTreeNode`. Yes, that definitely makes sense! Thanks for the pointers 😄 

(and sorry for bothering you on a Sunday, I did not expect an answer tbh...)

**Comment by osmers** [comment]
Hey :) so the idea was to have a list of all languages in that region in alphabetical order. And then just gray out the ones that cannot be selected/changed. An alternative would be to just name the ones the region has active that cannot be translated somewhere on the side, so they know that that is why they are not in the list. But then make them not selectable.

**Comment by osmers** [comment]
Unchecked, I'd assume - bcs they are not translateable

**Comment by charludo** [comment]
> * In all places where machine translations are generated, first check whether the corresponding language is enabled for machine translations in this region.

Just a heads up, I have not yet implemented this in #2036. I'd rather create a separate issue for this, seeing as the conditions from #1831 should probably be checked at the same time.
