### ISSUE TITLE
Show success message when page/event/location was automatically saved

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2002]
### Motivation
Some users are not very clear about when changes are saved automatically. This leads to uneasiness with the system which should be avoided

### Proposed Solution
Add information about the save draft function on the editor page itself. E.g. in the form of a text that informs the user that their changes have been saved - similar to Wordpress ([here](https://publishpress.com/blog/wordpress-publishing/autosaves/#:~:text=Fortunately%2C%20autosaves%20are%20a%20WordPress,one%20autosave%20at%20a%20time.) or [here](https://wordpress.com/de/support/editoren/beitrags-und-seitenrevisionen/#:~:text=Speichern%20und%20die%20automatische%20Speicherung,-Deine%20vorgenommenen%20Änderungen&text=Oben%20rechts%20im%20Editor%20siehst,alle%20Beiträge%20und%20Seiten%20aktiviert.)

### Alternatives
Leave users to guess when a page has been saved and only make it visible in the page tree 

### Design Requirements
Als Nutzer möchte ich sehen, wann meine Änderungen zwischengespeichert wurden. 
Als Nutzer möchte ich ggf die Möglichkeit haben, diese Zwischenspeicherung selbst auszulösen. 

As a guidance for the design please have a look at the way it's implemented in Wordpress

**Comment by PeterNerlich** [comment]
I propose a text like "Saved 25 seconds ago" (rounded to 5 s). I don't think the text even needs to stand out.

I could even imagine storing the content sent on the last save in another variable and comparing the current state to it on every keypress (maybe debounced/rate limited, but that are technical details), and showing "Changes waiting to be saved" (or not even anything) if it differs and "All saved!" or similar when it does not. This second method would have the advantage that it informs the user about the *state* of their changes instead of only of the *time* since their state was recorded, whatever it was back then.
