### ISSUE TITLE
Broken-Link-Checker should divide in errors/warnings

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#2077]
### Motivation
To keep it simple for municipalities the results should be divided not only in valid and invalid, but in valid, error and warning.
"Ungültig" should be renamed in "Fehlerhaft".

### Proposed Solution
404 and "Ungültige URL" should be visible in error-section
all other error(-code)s should be visible in warning-section

For reference: This topic was debated earlier in #1695

**Comment by timoludwig** [comment]
Wouldn't it make more sense to be more honest with the division and name the categories "Not found / Nicht gefunden" and "Invalid / Ungültig"?

To me, "Warning" sounds a bit like "well, not ideal, but doesn't need my direct attention", which is not at all what this category is about. These errors are very real and the links are just not working in most cases. We can still try to minimize the false positives by contributing to the link checker library:

- https://github.com/DjangoAdminHackers/django-linkcheck/issues/125
- https://github.com/DjangoAdminHackers/django-linkcheck/issues/153
- https://github.com/DjangoAdminHackers/django-linkcheck/issues/159

**Comment by osmers** [comment]
How far do you think we can limit false positives? Bcs from the ones I checked, I'd say about 50% worked just fine. The other 50% were faulty. I know that some of the ones that worked are technically not 100% correct, but it's not something the Kommunen have the time to address.

**Comment by timoludwig** [comment]
Hard to estimate without trying it, I already implemented a few improvements in the link check library, which should resolve most of the false positive 403 errors... as soon as they release a new version, we can check all links again and test how much it already improved the situation.

**Comment by osmers** [comment]
Alright, then let's take that step first and then have a look. 
What would be even more interesting are the less understandable codes like: Connection Error: HTTPSConnectionPool(host='www.kl- or New Connection Error: Failed to establish a new connection: [Errno -2] Name or service not known bcs both pages work just fine when I click on the link
Those would be pages we'd definitely want to put under warning since they almost always work...

**Comment by timoludwig** [comment]
Hmm, those are quite unique problems:
- https://www.baf%C3%B6g.de/de/bafoeg-auch-ohne-deutschen-pass-591.php
  This is an encoding problem of the umlauts in the domain (e.g. https://www.xn--bafg-7qa.de/de/bafoeg-auch-ohne-deutschen-pass-591.php would work), not sure if this is incorrect and just happens to work in the browser because browser often times make incorrect things work, or if this is totally valid and just the library cannot handle it. I will open an issue in the library for this and further investigate.
- https://www.kl-inklusiv.de/
  They use a very strange web server which does not really comply with HTTP standards it seems:
```
curl -I https://www.kl-inklusiv.de/
HTTP/1.1 404 Not Found
Date: Mon, 06 Mar 2023 11:57:56 GMT
Server: waitress
Content-Length: 26
Content-Type: application/json
Via: waitress
X-Powered-By: Zope (www.zope.org), Python (www.python.org)
```

**Comment by timoludwig** [comment]
Well, I'm still not convinced we really need a new category for these - we already have a category for false positive errors: the "ignore" category.

There will always be certain edge cases where the checker does not behave exactly like a user's browser. There is no need for region managers to contact the service team in such cases - they should just ignore a link after they manually checked it. Maybe we should put this information in the wiki? Or directly on the link checker page in the CMS?
