### ISSUE TITLE
Store the HIX value of pages in the database

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-cms#2101]
### Motivation
We want to prevent the automatic translation of hard to understand page texts, where hardness is measured by the HIX score. Calculation of this score is too slow/expensive to do "on the fly" for large numbers of pages, so instead we need to store it in the database.

### Proposed Solution

- [x] Store the score in a new field on the page model and recalculate and update it every time the page is saved.
- [ ] Add management command to populate the hix values of all page translations which have not been saved yet

### Alternatives

Store the entire history of HIX scores per page, opening up analytics possibilities. 

### Additional Context

- Quick side note from a chat with @dkehne. The automatic translations should be possible if the HIX value is greater or equal to 15 and not greater than 15. (Author: @JoeyStk, March 6th 2023)

### Blocking:
- #2088 
- #2102

**Comment by david-venhoff** [comment]
Johannes and I have thought a bit about possible implementations for this issue, but we are not really sure how to proceed.

What we thought about:
- Store the hix value in the database when the user clicks on update in the hix widget: This would probably cause many pages to have no hix score, so automatic translations are not possible / only possible after the user manually updates every hix score
- Store the hix value when the user updates a page: This could make saving a page quite slow, since we would have to wait for the hix api to answer
- Calculate the hix score in the background: probably the simplest solution for users, but could be difficult to implement. We might need to have a persistent queue of pages, a bit similar to the link checker.

Are there maybe better solutions than the ones listed above? Or do you have a preference for one of these?

**Comment by timoludwig** [comment]
In order for this to work, we need two components that are separate from one another:

1. We need a possibility to populate the database with all hix values, independently from their saving process. For this task, I suggest implementing a management command (after #2071 is merged) which iterates over all pages and queries the hix value (ideally, this would make use of aiohttp to query multiple values at the same time, not sure what the rate limits are here, but we can play with this around later). We could then start this command e.g. on a weekend to avoid putting unnecessary strain on the server.

2. We need a possibility to update the hix value after a page is saved, I like your idea with the background task similar to the link checker. I'm not even sure if we even need a persistent queue... Couln't we just add a normal post save signal handler that queries the hix score and stores it? There won't be much race conditions like in the link checker, because the hix values of pages are completely independently from another (unlike the link checker where many links can point to the same URL)...

I also think these two components can be developed separately, maybe 2. first and then 1. only needs to calculate those values that are missing after some time (when we decide to launch the MT feature)...

**Comment by timoludwig** [comment]
I think my suggestion for 1. was more complicated than needed: Since this is an operation we only need once, I guess a management command would not be appropriate.
Instead, we can just populate the HIX values via the Django shell:

`integreat-cms-cli shell`
```
from integreat_cms.cms.models import PageTranslation
for page_translation in PageTranslation.objects.filter(language__slug="de").distinct("page"):
    page_translation.save(update_timestamp=False)
```
And the post-save signals will take care of the rest.
Since we have ~25k pages in the database that need to be updated, this will take quite a while (several hours at least), but that should not be a problem, we should just monitor the logs for any unexpected errors.
If you agree, we can close this issue as completed.

**Comment by svenseeberg** [comment]
Do we actually need HIX values for all past versions? At least from an organizational perspective this would not be necessary. IMHO we can also just set it to 0 in all older versions? If a version is reverted, a newer version will be created anyways, right?

**Comment by timoludwig** [comment]
@svenseeberg Indeed, all suggested solutions only update the hix value of the latest versions and keep the value of the old versions to the default None.

**Comment by svenseeberg** [comment]
Ah right, we have 25k pages w/o versions. The number seemed too large.
