### ISSUE TITLE
Create a design for language tabs

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#2108]
### Motivation

We want to refactor our language tabs so they are also accessible from smaller screens. For that we need a design. 

### Proposed Solution
Come up with a design that also works on mobile screens

### Alternatives
None

### Additional Context
This blocks: 
- #1815

This is what the language tabs look like right now: 
![grafik](https://user-images.githubusercontent.com/72705147/223115516-feb24e36-8c00-4e6c-89e4-04c4d1be5cbe.png)

### Design Requirements

User-Story: I, as user of the cms, want to view the language tabs in a decent way from my mobile phone, laptop and tablet - with and without zoom (ca. 125%)

Figma-File: https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=518%3A3671
@hauf-toni

**Comment by timoludwig** [comment]
My suggestion would be the following:
- On very wide screens which fit all of them, we
  <details>
    <summary>show all tabs</summary>

  ![Screenshot 2023-03-12 at 13-21-11 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/224544534-f642f180-dad7-4813-84a7-8b7b7359b9d0.png)

  </details>
  
- On all screens which fit at least 2 tabs (but not all), we
  <details>
    <summary>show the current language plus as many as possible, and the "other languages" dropdown</summary>

  ![Screenshot 2023-03-12 at 13-21-58 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/224544623-7dfa98bf-a071-47ce-b632-cc466f84b9a1.png)
  ![Screenshot 2023-03-12 at 13-22-29 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/224544629-b84f2ca1-55bf-47bd-afa8-7220b217e072.png)

  </details>
    
- On all screens which only fit one tab, we either
  <details>
    <summary>replace the "other languages" text with another icon</summary>

  ![Screenshot 2023-03-12 at 13-36-47 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/224545135-df11371e-f87c-4383-8216-2b1b4a1cfe0e.png)

  </details>
  <details>
    <summary>omit the text completely,</summary>

  ![Screenshot 2023-03-12 at 13-33-35 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/224544960-70b25bb8-617e-4392-b9cc-b2005c126d62.png)

  </details>
  <details>
    <summary>or show the dropdown chevron inside the one tab</summary>

  ![Screenshot 2023-03-12 at 13-24-39 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/224544654-492b06f9-6893-4b07-8874-a5d2ecb3cc27.png)

  </details>
    
- All screens which are even smaller are probably unusable for content creation anyways, I don't think we need a separate solution for that.

Since we don't know how many tabs fit onto the screen until we have rendered them, this solution would have to be implemented in JS.

**Comment by JoeyStk** [comment]
This is a duplicate to #1815

**Comment by timoludwig** [comment]
@JoeyStk I thought you intentionally created two issues for this - one design issue for UI/UX team and one implementation issue? But yeah, I'm fine with handling both in the same issue.

**Comment by JoeyStk** [comment]
Yes, I created it intentionally for this exact reason, but the consensus in our call with ui/ux was to do it in the same issue :smile:

**Comment by hauf-toni** [comment]
@timoludwig great job, your suggested solution is ideal to cover different hardware sizes. for the smallest screensize, I would definitely go for the first solution suggestion ("- replace the "other languages" text with another icon"). suggestion 2 and 3 are a. inconclusive, as only by interacting with the tab can you find out what is triggered and b. do not meet accessibility requirements
