### ISSUE TITLE
Use cached HIX score in HIX widget when possible

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-cms#2144]
### Motivation

Since the HIX score is now being stored in the DB, we can save ourselves unnecessary calls to the Textlab API and reduce loading times in the page form view by fetching the score to be displayed in the widget from the DB whenever possible.

### Proposed Solution

Only call to the Textlab API when either of the folliowing is true:
- HIX score has not been calculated and saved to the DB yet
- a new German page translation has been saved, so the score needs to be updated
- user presses "refresh" in the HIX widget

On all other occasions (e.g. when opening the page editor view) simply get and display the value from the DB.

### Alternatives

Don't

**Comment by timoludwig** [comment]
Cool idea! We could also go the other way round and write the value that is calculated in the hix widget back into the form value (and only clear it again when the content is changed / the value is outdated).
This way, we would not have to retrieve the value again in the post save signal, because it's already saved during the normal form save.
Not sure if this would be another issue or part of this one.

**Comment by charludo** [comment]
> This way, we would not have to retrieve the value again in the post save signal, because it's already saved during the normal form save.

Wouldn't this make it fairly trivial for a user to tamper with the HIX score?

**Comment by charludo** [comment]
I think it also makes the logic a little easier, no need to check if the user manually calculated the Score.
