### ISSUE TITLE
Incorrect text direction in push notification form for RTL languages

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#2166]
### Describe the Bug

The push notification form is from left to right, even for right to left alphabets

### Steps to Reproduce

1. Go to "news"
2. Create news
3. Click on tab for rtl language, e.g. Arabic
4. Try to enter text

### Expected Behavior

The input field should have the correct text direction

### Actual Behavior

It's always left to right

### Additional Information
Set the `dir` attribute of the textarea to `rtl` for those languages
```
<textarea dir="rtl"></textarea>
```

**Comment by JoeyStk** [comment]
After playing around with this for a while, I now think that there are in total two issue:
1. As described above for RTL the input and text area fields should be RTL
2. But also I noticed, that the navigation via tabs is not working (at least for me). When I'm in the news form and I click on any language tab the UI looks as if I had changed language, but the URL still remains for German. 
![grafik](https://user-images.githubusercontent.com/72705147/227987355-9b19f879-9319-4ed9-8de2-66e4435d01ff.png)
I would expect the URL to be http://localhost:8000/augsburg/push-notifications/bg/new/ instead of http://localhost:8000/augsburg/push-notifications/de/new/. Do you have the same issue and as is my assumption correct?

**Comment by JoeyStk** [comment]
Ok, thank you for clarifying. I need to spend some more time on this then :smile:
