### ISSUE TITLE
Timed Push Notification

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#2186]
### Motivation

Users want to write push notifications in advance, but not send them directly. Instead, a time should be defined at which the notification should be sent.

### Proposed Solution

Add a timing box to the content form for Push Notifications where a time can be defined at which the notification should be send to the user. We can probably copy a lot from the event form and use some kind of in-built job to send the Push Notifications at the desired time.

As a initial step we won't a recurring feature and stick with a simple time step.

### User Story

- As a CMS-User I want to define a time for a push notification so that I don't have be at the computer when a notification is supposed to be send to the user.

### Additional Context

Possible timing component: https://django-extensions.readthedocs.io/en/latest/jobs_scheduling.html

**Comment by timoludwig** [comment]
> This sounds like effort: high to me,

Agreed.

> Possible timing component: https://django-extensions.readthedocs.io/en/latest/jobs_scheduling.html

This doesn't help us very much, since it only runs jobs at a given schedule, not at a given point in time. So this extension essentially provides cron jobs, which we can also run on the server natively. We could e.g. define a management command that sends out all timed push notification of the current time window and execute this all 5 minutes or so (depending on how fine graded we allow them to sent the notifications... probably hourly or half-hourly would also be ok)

If we want to go with a python-only solution, we could also have a look at https://apscheduler.readthedocs.io/, but this definitely adds quite a lot of dependency code... and I'm not sure if running a permanent scheduler in the background is really justified for the (probably very limited) usage of timed push notifications...
