### ISSUE TITLE
Add management command to automatically fix broken internal links

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#2205]
### Motivation

In some cases, broken internal links can be fixed automatically, e.g. when:
- A parent page has been moved, so the slug is identical but the path is not correct anymore
- The slug of a page has been changed, so a link might reference an older version of a page

### Proposed Solution

In those cases, determine the correct link of the latest versions of those translations and replace it in the content.

### Alternatives

Manually fix the links or implement a workaround in the app to request the latest slug via the API

### Additional Context

Related issues:
- #2174
- #1587
- https://issues.tuerantuer.org/browse/IGAPP-1050

**Comment by seluianova** [comment]
As I see, currently when we do internal link checking, we find a content object, compare its actual url to the link being checked, and mark the link as invalid if they don't match.

If I add a management command to fix internal links, the mechanism will be basically the same:
Find content object --> get its actual url --> compare with the broken link --> replace if required.

So I wonder why we want to fix these links separately by running a management command?
Maybe we could fix them as soon as we detect them?
Because at this point we have all the necessary data and only the replacement itself remains.

**Comment by timoludwig** [comment]
@seluianova Yes, this would be possible, but it might also cause a lot of overhead during content creation and potential race conditions with e.g. autosaves or subsequent page updates... Since the link scanning process is triggered via the post save signal of pages, we might have many side effects of this functionality...
So a more conservative approach would be to run this e.g. as weekly cron job or similar...
