### ISSUE TITLE
Enable link checker for organization website URLs

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2369]
### Motivation

When the website links of organizations are no longer working, we don't notice it

### Proposed Solution

Include the website fields of urls in the link checker

### Alternatives

Don't do it

### User Story

As a region manager, I want to know when the URL of one of my organizations is no longer working

**Comment by MizukiTemma** [comment]
Do not forget adding it to `replace_link` too. See #2982

**Comment by juliankehne** [comment]
@timobrembeck @osmers

I tested this and have some feedback:

1. Inconsistency across user roles: As far as I know only the manager role should be able to edit organizations. With this feature other roles with access to the Broken Links can change the organization URL from the Broken Links overview, e.g. the editor role.
2. In the Broken Link overview you can click on the source of an URL to get redirected to the page its used in. For an organization URL I would expect it to do the same and redirect to the Organization, at least for the manager role as only they can access organizations. Currently nothing happens and there is no visual indication why it doesn't work, e.g. tooltip when hovering over it.
![2024-10-07 13_06_03-Window](https://github.com/user-attachments/assets/f44346d6-0ecd-47a5-b85f-5cbaa849ba45)
3. There is no clear indication in the UI that an URL belongs to an organization

I'm not 100% sure about this, but the URLs from the imprint behave similar, also regarding the user role that should be able to edit the imprint.

Otherwise the organization URLs do show up in the right categories (valid, invalid, etc.) and can be changed in the Broken Links page directly. Ignoring, Unignoring and Rechecking do work with bulk execution.

**Comment by osmers** [comment]
> 1. Inconsistency across user roles: As far as I know only the manager role should be able to edit organizations. With this feature other roles with access to the Broken Links can change the organization URL from the Broken Links overview, e.g. the editor role.

That's a very good catch. Needs to be changed for the imprint as well.
