### ISSUE TITLE
Feedback archiving does not work 

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2399]
### Describe the Bug

After archiving one or multiple of feedback, they stay in the list of feedback and don't go to the archived list, although the success messsage was shown.

### Steps to Reproduce
This behavior has been observed in Testumgebung in the live system but I cannot reproduce it in the development enviroment.

### Expected Behavior

Archived feedback objects are shown in the archived list.

### Actual Behavior

Arvhied feedback objects are shown in the (normal) feedback list.

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by david-venhoff** [comment]
This bug happens when redis is activated. I tried to fix it using the `invalidate_obj` solution already used in the other commands in the feedback_actions files, but it does not seem to correctly invalidate all relevant queries. The only working solution I found was to call `invalidate_model(Feedback)`, but that is not a very good solution.
