### ISSUE TITLE
Add Save button for sent News

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#2429]
### Describe the Bug
Before the 2023.9.0 release there was a "Save" button that allowed editing sent News. Currently, there is only a "Save as Draft" button which returns the message to draft status with no way of publishing it again.

### Steps to Reproduce

1. Create a push notification
2. Send it
3. Edit the notification and Save as Draft
4. There is no button to publish again (w/o sending to FCM again!)

### Expected Behavior
It should be possible to pull a News item from the API (App) but also to change the text if required.

### Actual Behavior
There is only a "Save as Draft" button.

**Comment by svenseeberg** [comment]
We tested all available paths, this cannot be reproduced. The only option is using the "Save as Draft" button after a message has been sent.

**Comment by svenseeberg** [comment]
The problem has been found: there is only a "Save as Draft" button for sent news. The first post is updated accordingly.

**Comment by osmers** [comment]
So the problem seems to be that during a previous update of the news feature, the save button was removed and only save as draft button remains. Since this is leading to some confusion with users, I would add the prio high label and inform users who report this issue of a work around (save message they want to ammend as draft, create a new message with the changed details and send it again - only until we have the button back)

**Comment by timobrembeck** [comment]
@osmers The good news is that only the label of the button is incorrect, its function is still unchanged. This means that every update is immediately visible in the app, even if "save as draft" is clicked.

**Comment by osmers** [comment]
@timobrembeck are you sure? Bcs the problem became known bcs the Malteser used that button and the messages were not shown in the app anymore. Which I assume means, that they were saved as a draft.

**Comment by timobrembeck** [comment]
@osmers ahh sorry, no you're right, the news really disappear when using this button.
