### ISSUE TITLE
Sometimes wrong city automatically selected when creating POI

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2444]
### Describe the Bug
When creating a POI, sometimes the wrong city is automatically inserted (probably bcs it is wrong in the database) and cannot be changed

### Steps to Reproduce

1. Go to https://admin.integreat-app.de/testumgebung/pois/de/3759/edit/
2. See city name of Wersau (should be Brensbach)
3. Change the city name to Brensbach
4. See that is automatically changes back to Wersau

### Expected Behavior
I should be able to fix the city name if it is incorrect

### Actual Behavior
System changes city back to name from database

### Additional Information
![image](https://github.com/digitalfabrik/integreat-cms/assets/64901227/d749e408-a0b5-42f2-bd28-f44cead5a0d2)

### Proposed solution ###
Introduce a new checkbox right below the input field for the city called "Fill city out automatically (Stadtnamen automatisch ausfüllen)"
The tick is always set
When removing the tick, users should be able to change the city name without the system changing it back

**Comment by david-venhoff** [comment]
Is there a reason why we currently update the city name if it is already filled in? As far as I understand, if the city field is not empty, changing it does not really make sense since we also use the city for the nominatim request (So if the request returns something, the city name should already be correct).
In that case the simplest fix would be to not update the city name at all if it is not empty.

**Comment by osmers** [comment]
That would also work :) either way is fine by me, as long as municipalities can then change a city name by themselves :)

**Comment by osmers** [comment]
Not sure if using the box they can tick/untick explains better what happens, but in general it should not be too difficult to understand for them :)
