### ISSUE TITLE
Client side validation in event form

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#246]
In the event form, certain fields depend on other fields and only specific combinations are possible. To enhance the user experience, we should add the "required"-attribute via Javascript whenever the associated checkbox is activated and vice versa.
Example:

- [x] `start_time` and `end_time` should be required when `is_all_day` is not checked.
(fixed in 5426559e25114897d99773e57bed39191c3391fe)
- [ ] `recurrence_end_date` should be required when `has_recurrence_end_date` is checked.

**Comment by timoludwig** [comment]
@florianhofhammer I unassigned you since I wasn't sure whether you wanted to complete the issue - if you're still interested though, I can of course re-assign you :wink:
Greetings from Berlin!

**Comment by theresantonie** [comment]
Looking at the existing code under 
[/integreat-cms/cms/forms/events](https://github.com/digitalfabrik/integreat-cms/tree/develop/integreat_cms/cms/forms/events),
where the first part of the issue was fixed at
[event_form.py[124-147]](https://github.com/digitalfabrik/integreat-cms/blob/4d5c8a6dd70a736560a21b4c4c461cecf763289f/integreat_cms/cms/forms/events/event_form.py#L124-L147),
it seems as if the second part of the issue was already fixed when the recurrence_rule_form.py script was created:
[recurrence_rule_form.py[112-122]](https://github.com/digitalfabrik/integreat-cms/blob/4d5c8a6dd70a736560a21b4c4c461cecf763289f/integreat_cms/cms/forms/events/recurrence_rule_form.py#L112-L122)
