### ISSUE TITLE
Cannot assign authors and editors in a brand new page

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2482]
### Describe the Bug

It is not possible to add an user as author and editor while creating a brand new page, although this section is shown and there is no warning.

### Steps to Reproduce

1. Create a new page
2. Go to the section "Additional permissions for this page"
3. Add an user as author or editor
4. Save and open the page again to find the assignment not saved

### Expected Behavior

Either this section is hidden until the first save, or save the assignment successfully

### Actual Behavior

No error, page save succeeds but the assignment is not saved. See the trace back which appears when clicking on "Add to authours/editors"

### Additional Information

<details>
 <summary>Traceback (most recent call last):
</summary>

  ```
  File "/home/micucu/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/micucu/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/micucu/integreat-cms/.venv/lib/python3.9/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/micucu/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/micucu/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/micucu/integreat-cms/integreat_cms/cms/views/pages/page_actions.py", line 628, in grant_page_permission_ajax
    "page": page,
UnboundLocalError: local variable 'page' referenced before assignment
  ```

</details>

**Comment by JoeyStk** [comment]
I had a look into this issue. The issue seems to be that the button and ultimately the page [doesn't have an id during the creation process yet](https://docs.djangoproject.com/en/dev/ref/models/instances/#saving-objects). Therefore the button is clickable once it was saved for the first time (and the page has received an id). Although I think it's more desirable for users to be able to set the permissions at any point (including the creation), I don't think there is a quick fix for it. The only way I could think of would have been [to set ids manually](https://docs.djangoproject.com/en/dev/ref/models/instances/#auto-incrementing-primary-keys). As the documentation says this holds risk and I think it's probably not worth to take it at this point.

Therefore I would propose to:
-  add a help text to the page form during it's creation process stating that the page needs to be saved first until permissions can be set
- adding a condition to the button to only be shown if a page id exists, which would result in it not being shown until the first save of the page

Is this fine with you or do you have any objections or other ideas for it?

**Comment by MizukiTemma** [comment]
@JoeyStk 
Thank you for having a look in to this. Yes, I agree with your suggestion 🙂
