### ISSUE TITLE
New Dashboard: Change the order of To-Dos

### ISSUE THREAD

**Issue by vthejay** [digitalfabrik/integreat-cms#2553]
### Motivation

In the new dashboard, the order of the the To-Do items need to be changed, from an impact perspective.

### Proposed Solution

The order as decided upon in the Service-Team meeting today:

1. Broken links
2. Outdated paged
3. Pages with low HIX score
4. Unread Feedback
5. Pages pending approval
6. Automatically saved pages

**Comment by timobrembeck** [comment]
@vthejay Thanks for reporting the issue! :+1:

A few small suggestions for the future:

- The two topics are different from each other since the "review" wording impacts other places of the CMS as well, not only the dashboard. Thus it makes sense to open a new issue for it (I opened #2554).
- Please write the issue description in English, when quoting parts of the CMS UI, then please change your UI language to "English" in the user settings.
- If neither the bug nor the feature request seem appropriate, please just select the one that fits better (in this case, the improvement of an existing feature is more similar to a feature request than to a bug) and delete all parts of the issue template that are not needed for this issue (e.g. the "description of the bug", "steps to reproduce" etc.). Also, remove any labels that were automatically applied by the template if they don't fit (like the "bug" label in this case).
