### ISSUE TITLE
Allow "Opening hours" to be switched off temporary if that is needed  

### ISSUE THREAD

**Issue by nassabay** [digitalfabrik/integreat-cms#2564]
### Motivation
There might be cases where user want/have to switch "Opening hours" temporarily off. But actually, as soon as users edit the "opening hours" the first time, they always have to edit it. 

### Proposed Solution
Allow removing "Opening hours" any time. Switch them temporary off.

### Additional Context
Go to Testungebung  -> Orte
For the location, change "Opening hours"  and save.
Save the page and see the changes in "Karte"
Now switch "Opening hours" off
It is not possible

**Comment by timobrembeck** [comment]
I think this is not necessary, since there are already two possibilities to disable the opening hours:
1. Mark the location as "temporarily closed" – this keeps the opening hour information and just hides it temporarily.
2. Edit all days at once and mark them as closed – this is the initial state when the POI was created.
