### ISSUE TITLE
Add "keep direction" functionality to do not translate function

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2854]
### Motivation
With the new phone number format, phone numbers are written with spaces between them.
![image](https://github.com/digitalfabrik/integreat-cms/assets/64901227/3fae36c4-8d78-47cf-85ae-5904d1abcff6)
This means that when translating this number into rtl languages, their order gets mixed up: 
![image](https://github.com/digitalfabrik/integreat-cms/assets/64901227/3563a176-7e47-4c5f-b9a0-d19f038296dd)

### Proposed Solution
Extend the do not translate function with the function that texts keep their direction: e.g. all texts that are marked as do not translate are always ltr

### Alternatives
Add an extra button if the municipalities want to keep direction and keep the functionality seperate from do not translate (not recommended bcs it adds extra difficulty and possibilites of making mistakes)

### User Story
As a user of the app I want to read the phone number in the correct order, even when using the app in rtl languages so that I always dial the correct number. 
As a CMS user I want no extra work when using formatted phone numbers and translating content so that I can keep the time I need to work on Integreat as low as possible.

### Additional Context
Mattermost Thread: https://chat.tuerantuer.org/digitalfabrik/pl/zu3x4bscy7bcfgen8p7fgngacc
@svenseeberg already tested the function and it seems to work, even between two rtl texts...
![image (5)](https://github.com/digitalfabrik/integreat-cms/assets/64901227/4f8ff345-8072-436a-8a4b-51068c6c4112)

### Design Requirements
None since it will be an invisible functionality.

**Comment by svenseeberg** [comment]
The `<span>` element can get a `dir="ltr"` to achieve that. AFAICT it should not be harmful in any way, as by definition the content is not translated (and should therefore also remain ltr).

**Comment by JoeyStk** [comment]
I couldn't get it to work. I added `direction:ltr` to the `do-not-translate span`. That didn't work. Also adding it to the telephone link didn't work. 

This is because the parent element `<p style="direction: rtl; ;text-align: right;"><a class="link-external" style="direction: ltr;" href="tel:+491111111" data-bcup-haslogintext="no"><span class="notranslate" style="direction: ltr;" translate="no">+49 (0) 1111111</span></a></p>` overwrites it with rtl again. I tried to manipulate this and set the closest p to ltr, how a. it was still overwritten and b. even if it worked, then we would have problems with the other elements within that parent element. 

Any further ideas are welcome! @svenseeberg

**Comment by svenseeberg** [comment]
`<span dir="ltr">` does work AFAICT.

**Comment by PeterNerlich** [comment]
Not actually fixed on app side. Proposing to add the attribute `dir="ltr"` to every element marked with notranslate during the server side normalization step before saving any translation to db

**Comment by osmers** [comment]
@PeterNerlich @charludo any progress since the two new apps are going live tmr?

**Comment by PeterNerlich** [comment]
@osmers  I will look at this today
