### ISSUE TITLE
CSV export feedback

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#310]
Some cities want to export their feedback.

**Comment by timoludwig** [comment]
This is blocked by #32 (View feedback).

**Comment by osmers** [comment]
Since I just got a request from a municipality regarding this issue, I wanted to open it up for discussion - especially how comprehensive it is? Is the effort low, medium or high? Then I can discuss it with the team - but since there is no other way for export (e.g. via API as with POIs) it might be a worthwhile issue to put into Q1

**Comment by timobrembeck** [comment]
I'd say the effort is low - medium, so should be doable in 24Q1.
