### ISSUE TITLE
[2024-11-07] Recurring events are not imported correctly

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#3110]
### Describe the Bug

When importing recurring events only the original event is shown in the Events page, marked as a One-Time. All types of recurring events are affected, daily, weekly, etc.

### Steps to Reproduce

1. Go to Nextcloud calendars and create a new recurring event.
2. Import calendar through the iCal 
3. See event is imported as a one-time event, not as a recurring event.

### Expected Behavior

Event should be correctly imported as a recurring event.

### Actual Behavior

Event is wrongfully imported as one-time event.

**Comment by JoeyStk** [comment]
(Partially) blocked. The refactoring can be done anytime already

**Comment by david-venhoff** [comment]
In todays meeting, we decided against refactoring the recurrence rule model, because it would be too much work. Instead, we will make a best effort to map ical rrules to our existing recurrence rule model, and fail if that is not possible. 

For future reference, a (very wip) branch attempting to rewrite the recurrence rule model can be found here: https://github.com/digitalfabrik/integreat-cms/tree/refactor/recurrence_rule
